[project]
name = "mlflow-labs"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "mlflow-skinny>=3.3.1",
    "notebook>=7.4.5",
    "pandas>=2.3.2",
    "pandas-stubs==2.3.0.250703",
    "scikit-learn>=1.7.1",
]
